import React, { Component } 		from 'react';
import EcommerceBreadcumb 			from "../../blocks/common/Breadcumb/EcommerceBreadcumb.js";
import EcommerceHeader 				from "../../blocks/common/EcommerceHeader/EcommerceHeader.js";

import EcommerceFooter    			from "../../blocks/common/EcommerceFooter/EcommerceFooter.js";
import 'bootstrap/js/collapse.js';


import "./TermsAndCondition.css";

export default class TermsAndCondition extends Component {
	constructor(props){
    super(props);
	    this.state = {
	    	
	    	
	    };
  	}  
  	  


  render() {
		return (
				<div className="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12 backColorEF marginTop180">
					<div className="row">
						{/*<div className="col-lg-2 col-md-12 col-sm-12 col-xs-12 marginTop180 storeInfo">
							<div className="row">
								<div className="col-lg-12  col-md-12 col-sm-12 col-xs-12 backColorWhite storeInfo ">
									<label className="onHover"><span>STORE INFORMATION</span></label><br/>
										<ul className="productList1">
											<li className="onHover"><i className="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;123 Sky Tower, West 21th Street, Suite, NY</li>
											<li className="onHover"><i className="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;01923-456-789</li>
											<li className="onHover"><i className="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;info@domain.com</li>
										</ul>
								</div>
							</div>
						</div>
						<div className="col-lg-2 col-md-12 col-sm-12 col-xs-12  linkToOtherPage">
							<div className="row">
								<div className="col-lg-12  col-md-12 col-sm-12 col-xs-12 backColorWhite linkToOtherPage ">
									<label className="onHover"><span><a href="/PrivacyPolicy">Privacy Policy</a></span></label><br/>
									<label className="onHover"><span><a href="/termsandcondition">Terms And Conditions</a> </span></label><br/>
									<label className="onHover"><span><a href="/about-us">About Us</a> </span></label><br/>
									<label className="onHover"><span><a href="/contact-us">Contact Us</a> </span></label><br/>

								</div>
								
							</div>
						</div>
*/}
						<div className=" col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
							{/*<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<div className="row">
									<div className="col-lg-12 col-md-9 col-sm-9 col-xs-9 mt20 ">
										<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
											<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 backColorBread pull-right ">
											<span className="pull-right noStylea"><a href="#"> Home&nbsp;&nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp;&nbsp;</a><a href="#">Terms And Condition </a> </span>
											</div>
										</div>
									</div>
								</div>
							</div>*/}
								<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12  mt20  ">
									<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
										{/*<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 LabelContactUs row">
											<label>ABOUT US</label>
										</div>*/}
									
										<div className="col-lg-12 col-md-12 col-sm-12 col-xs-12 termsAndConditionsContainer backColorWhite ">
											<label className="">Terms And Conditions</label><br/><br/>
											<p className="">
											This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

												This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name www.className=.com (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)

												The Platform is owned by GangaExpress Internet Private Limited a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India (hereinafter referred to as "GangaExpress").

												Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with GangaExpress Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with GangaExpress.

												For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. <br/>GangaExpress allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean GangaExpress Internet Private Limited.

												When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.

												ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by GangaExpress Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
											</p>
											<span className="mt20 ruleHead"> Membership Eligibility</span>
											<p className="mt20">
												Use of the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the GangaExpress Platform and shall not transact on or use the Platform. As a minor if you wish to use or transact on Platform, such use or transaction may be made by your legal guardian or parents on the Platform. GangaExpress reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to GangaExpress's notice or if it is discovered that you are under the age of 18 years.
											</p>
											<span className="mt20 ruleHead"> Your Account and Registration Obligations</span>
											<p className="mt20">
												If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.

												Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.

												You agree that GangaExpress shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your display name in cases where You have failed to update Your revised mobile phone number and/or e-mail address on the Platform.


											</p>
											<span className="mt20 ruleHead">Platform for Transaction and Communication</span>
											<p className="mt20">
												The Platform is a platform that Users utilize to meet and interact with one another for their transactions. GangaExpress is not and cannot be a party to or control in any manner any transaction between the Platform's Users.<br/>

												Henceforward:<br/>
												<ul>
												<li> All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. GangaExpress does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by GangaExpress.<br/>
												 Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.
												</li><li> GangaExpress does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. GangaExpress does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. GangaExpress accepts no liability for any errors or omissions, whether on behalf of itself or third parties.
												</li><li> GangaExpress is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. GangaExpress cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform. GangaExpress shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.
												</li><li> GangaExpress does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.
												</li><li> GangaExpress does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.
												</li><li> At no time shall GangaExpress hold any right, title or interest over the products nor shall GangaExpress have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. GangaExpress is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.
												</li><li> The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. GangaExpress is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.
												</li></ul>
											</p>
											<span className="mt20 ruleHead">Charges</span>
											<p className="mt20">
												Membership on the Platform is free for buyers. GangaExpress does not charge any fee for browsing and buying on the Platform. GangaExpress reserves the right to change its Fee Policy from time to time. In particular, GangaExpress may at its sole discretion introduce new services and modify some or all of the existing services offered on the Platform. In such an event GangaExpress reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to GangaExpress Internet Private Limited.

											</p>
											
											<span className="mt20 ruleHead">Contents Posted on Platform</span>
											<p className="mt20">
												All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, "Content"), is a third party user generated content and GangaExpress has no control over such third party user generated content as GangaExpress is merely an intermediary for the purposes of this Terms of Use.

												Except as expressly provided in these Terms of Use, no part of the Platform and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, Platform or other medium for publication or distribution or for any commercial enterprise, without GangaExpress's express prior written consent.

												You may use information on the products and services purposely made available on the Platform for downloading, provided that You 

												(1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.

												You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Platform (collectively, "Content"). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.


											</p>
											
											<span className="mt20 ruleHead">Privacy</span>
											<p className="mt20">
												We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at Privacy. If You object to Your Information being transferred or used in this way please do not use Platform.

												We may share personal information with our other corporate entities and affiliates. These entities and affiliatesmay market to you as a result of such sharing unless you explicitly opt-out.

												We may disclose personal information to third parties. This disclosure may be required for us to provide youaccess to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.

												We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.

												We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.



											</p>
											

										</div>
	
									</div>
							</div>
						</div>

					</div>
				</div>
		);
	}
}
